[package]
name = "nyar_valkyrie"
version = "0.0.4"
authors = ["192608617@qq.com"]
edition = "2018"
description = "..."
license = "MPL-2.0"

[dependencies]
pest = "2.1.0"
# pest_derive = "2.1.0"

nyar_ast = {path = "../nyar-ast", version = "0.0.3"}
lazy_static = "1.4.0"

[dev-dependencies]


[build-dependencies]
