[package]
name = "nyar_valkyrie"
version = "0.0.1"
authors = ["192608617@qq.com"]
edition = "2018"

[dependencies]
pest = "2.1.0"
# pest_derive = "2.1.0"

nyar_ast = {path = "../nyar-ast"}
lazy_static = "*"

[dev-dependencies]


[build-dependencies]