[package]
name = "nyar_valkyrie"
version = "0.0.1"
authors = ["192608617@qq.com"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"

[dev-dependencies]


[build-dependencies]
# lalrpop = "0.16"
pest_generator = "2.1.1"
quote = "1.0"