[package]
name = "nyar_ast"
version = "0.0.2"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
license = "MPL-2.0"

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.45"


[dev-dependencies]

[features]
