[workspace]

members = ["projects/*"]
default-members = [
    "projects/-pre-build",
    "projects/nyar-ast",
    "projects/valkyrie-parser",
    "projects/vanilla-parser",
    "projects/vampire-parser",
]